// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAybBsL9KvJnCYBy9COlAfrJX4vX7Jk7vM',
    appId: '1:154616936348:web:e79c14152f6771e170fa59',
    messagingSenderId: '154616936348',
    projectId: 'dsatracker-df368',
    authDomain: 'dsatracker-df368.firebaseapp.com',
    storageBucket: 'dsatracker-df368.firebasestorage.app',
    measurementId: 'G-J1VNRS7MV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGAoQ9ToTN9Ejhej0OUUTJTY__Eh2VX8k',
    appId: '1:154616936348:android:c3ad1d271a8b4d3370fa59',
    messagingSenderId: '154616936348',
    projectId: 'dsatracker-df368',
    storageBucket: 'dsatracker-df368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPdGBq3NrHzu3Km_C-MIdleK-rjaKB5ek',
    appId: '1:154616936348:ios:5793d08829cba40270fa59',
    messagingSenderId: '154616936348',
    projectId: 'dsatracker-df368',
    storageBucket: 'dsatracker-df368.firebasestorage.app',
    iosBundleId: 'com.example.dsaTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPdGBq3NrHzu3Km_C-MIdleK-rjaKB5ek',
    appId: '1:154616936348:ios:5793d08829cba40270fa59',
    messagingSenderId: '154616936348',
    projectId: 'dsatracker-df368',
    storageBucket: 'dsatracker-df368.firebasestorage.app',
    iosBundleId: 'com.example.dsaTracker',
  );
}
